foodie/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sandbox/', include('sandbox.urls')),
    path('recipes/', include('recipes.urls')),
    path('comments/', include('comments.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('foodie_app.urls')),
]

foodie_app/urls.py
from django.urls import path
from . import views

app_name = 'foodie_app'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('recipes/<int:category_id>/', views.ShowView.as_view(), name='show'),
    path('new/', views.NewView.as_view(), name='create'),
]

recipes/urls.py
from django.urls import path
from . import views

app_name = 'recipes'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>', views.ShowView.as_view(), name='show'),
    path('new/', views.NewView.as_view(), name='new'),
    path('new/category/<int:category_id>/', views.NewView.as_view(), name='new_with_category'),
]

recipes/models.py
from django.db import models
from foodie_app.models import Category

class Recipe(models.Model):
    name = models.CharField(max_length=200, blank=False, null=False)
    description = models.TextField(blank=True, null=True)
    ingredients = models.TextField()
    instructions = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

recipes/forms.py
from django import forms
from foodie_app.models import Category
from recipes.models import Recipe

class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ['name', 'description', 'ingredients', 'instructions', 'category']
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Recipe Title'}),
            'description': forms.Textarea(attrs={'rows': 3, 'placeholder': 'Description'}),
            'ingredients': forms.Textarea(attrs={'rows': 5, 'placeholder': 'Ingredients'}),
            'instructions': forms.Textarea(attrs={'rows': 5, 'placeholder': 'Instructions'}),
        }

    def clean_category(self):
        category = self.cleaned_data.get('category')
        if not category:
            raise forms.ValidationError("Category is required.")
        return category

recipes/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render

from foodie_app.models import Category
from recipes.forms import RecipeForm
from .models import Recipe
from django.views.generic import ListView, DetailView, View

class IndexView(ListView):
    model = Recipe
    template_name = 'recipes/index.html'
    context_object_name = 'recipes'

class ShowView(DetailView):
    model = Recipe
    template_name = 'recipes/show.html'
    context_object_name = 'recipe'

class NewView(View):
    template_name = 'recipes/new.html'
    form_class = RecipeForm

    def get(self, request, *args, **kwargs):
        category = Category.objects.get(id=kwargs.get('category_id')) if 'category_id' in kwargs else None
        context = {
            'form': self.form_class(initial={'category': category} if category else {}),
            'category': category
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            recipe = form.save()
            return redirect('foodie_app:show', category_id=recipe.category.id)

recipes/templates/recipes/index.html
{% extends "base.html" %}
{% block page_header %}
    <h2>Recipes under {{ category }}</h2>
{% endblock page_header %}
{% block content %}
    {% if recipes %}
        <div>
            <div class="row">
                {% for recipe in recipes %}
                    <div class="col-sm-4">
                        <div class="card" style="width: 18rem;">
                            <div class="card-body">
                                <h5 class="card-title">{{ recipe }}</h5>
                                <h6 class="card-subtitle mb-2 text-body-secondary"><i>{{ recipe.date_added|date:'M d, Y H:i' }}</i></h6>
                                <p class="card-text">{{ recipe.description }}</p>
                                <a href="{% url 'recipes:show' recipe.id %}" class="card-link">Show</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    {% else %}
        <p>No recipes available.</p>
    {% endif %}
    <div class="mt-5">
        <a href="{% url 'foodie_app:index' %}" class="pt-5 link-primary link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">Back to Categories</a>
    </div>
{% endblock content %}

recipes/templates/recipes/new.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block page_header %}
    <h2>Add new Recipe {% if category %}to {{ category }}{% endif %}</h2>
{% endblock page_header %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form_errors form %}
        {% bootstrap_form form %}
        {% bootstrap_button button_type='submit' content='Save' %}
    </form>
    <div class="mt-5">
        <a href="{% url 'foodie_app:index' %}" class="pt-5 link-primary link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">Back to Categories</a>
    </div>
{% endblock content %}

recipes/templates/recipes/show.html
{% extends "base.html" %}
{% block page_header %}
    <h2>{{ recipe }}</h2>
{% endblock page_header %}
{% block content %}
    <div>
        <p>{{ recipe.description }}</p>
        <p><i>Ingredients:</i> {{ recipe.ingredients }}</p>
        <p><i>Instructions:</i> <div>{{ recipe.instructions }}</div></p>
    </div>
    <div class="mt-5">
        <a href="{% url 'foodie_app:show' recipe.category.id %}" class="pt-5 link-primary link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">Back to {{ recipe.category }}</a>
    </div>
{% endblock content %}