foodie/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sandbox/', include('sandbox.urls')),
    path('recipes/', include('recipes.urls')),
    path('comments/', include('comments.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('foodie_app.urls')),
]

sandbox/urls.py
from django.urls import path
from . import views

app_name = 'sandbox'
urlpatterns = [
    path('', views.index),
    path('foods/', views.RecipeListView.as_view(), name='food_list'),
    path('foods/<int:pk>', views.RecipeDetailView.as_view(), name='food_details'),
    path('tasty/', views.SpecificView.as_view(), name='tasty_recipes'),
    path('feedback/', views.feedback, name='feedback'),
    path('thank-you/', views.thank_you, name='thank_you'),
]

sandbox/models.py
from django.db import models

class Feedback(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    comment = models.TextField()
    satisfaction = models.CharField(max_length=10)

    def __str__(self):
        return f"{self.name} - {self.satisfaction}"

sandbox/forms.py
from django import forms
from sandbox.models import Feedback

CHOISES=[('satisfied', 'Satisfied'), ('neutral', 'Neutral'), ('dissatisfied', 'Dissatisfied')]

class FeedbackForm(forms.Form):
    name = forms.CharField(max_length=100, required=True)
    email = forms.EmailField(required=True)
    comment = forms.CharField(widget=forms.Textarea)
    satisfaction = forms.ChoiceField(choices=CHOISES, widget=forms.RadioSelect, required=True)

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if '@i.ua' not in email:
            raise forms.ValidationError("Email must be from i.ua domain.")
        return email

sandbox/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.views.generic import ListView, DetailView, View

from recipes.models import Recipe
from sandbox.forms import FeedbackForm
from sandbox.models import Feedback

def index(request):
    recipes = Recipe.objects.all()
    context = {
        'recipes': recipes
    }
    return render(request, 'sandbox/index.html', context)

def thank_you(request):
    return HttpResponse("Thank you for your feedback!")

def feedback(request):
    if request.method == 'POST':
        form = FeedbackForm(request.POST)
        if form.is_valid():
            Feedback.objects.create(
                name=form.cleaned_data['name'],
                email=form.cleaned_data['email'],
                comment=form.cleaned_data['comment'],
                satisfaction=form.cleaned_data['satisfaction']
            )
            return redirect('sandbox:thank_you')
    else:
        form = FeedbackForm()
    context = {
        'form': form
    }
    return render(request, 'sandbox/feedback_form.html', context)

class RecipeListView(ListView):
    model = Recipe
    template_name = 'sandbox/index.html'
    context_object_name = 'recipes'

    def get_queryset(self):
        filtered_recipes =  Recipe.objects.filter(category__name__iexact='Pizza')
        return filtered_recipes

class RecipeDetailView(DetailView):
    model = Recipe
    template_name = 'sandbox/show.html'
    context_object_name = 'recipe'

class SpecificView(View):
    def get(self, request, *args, **kwargs):
        tasty_recipes = Recipe.objects.filter(description__icontains='tasty')
        context = {
            'recipes': tasty_recipes
        }
        return render(request, 'sandbox/tasty_recipes.html', context)

sandbox/templates/sandbox/feedback_form.html
{% extends "base.html" %}
{% block content %}
    <h1>Feedback Form</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit Feedback</button>
    </form>
{% endblock content %}

sandbox/templates/sandbox/index.html
{% extends "base.html" %}
{% block content %}
    {% if recipes %}
        <h1>Food Items</h1>
        <ul>
            {% for recipe in recipes %}
                <li><a href="{% url "sandbox:food_details" recipe.id %}">{{ recipe }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No food items available.</p>
    {% endif %}
{% endblock content %}

sandbox/templates/sandbox/show.html
{% extends "base.html" %}
{% block content %}
    {% if recipe %}
        <article>
            <h2>{{ recipe.name }}</h2>
            <p>{{ recipe.description }}</p>
            <p><i>Ingredients:</i> {{ recipe.ingredients }}</p>
            <p><i>Instructions:</i> <div>{{ recipe.instructions }}</div></p>
        </article>
    {% else %}
        <p>No description available.</p>
    {% endif %}
{% endblock content %}

sandbox/templates/sandbox/tasty_recipes.html
{% extends "base.html" %}
{% block content %}
    {% if recipes %}
        <h1>Tasty Items</h1>
        <ul>
            {% for recipe in recipes %}
                <li><a href="{% url "sandbox:food_details" recipe.id %}">{{ recipe }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No tasty items available.</p>
    {% endif %}
{% endblock content %}