foodie/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sandbox/', include('sandbox.urls')),
    path('recipes/', include('recipes.urls')),
    path('comments/', include('comments.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('foodie_app.urls')),
]

foodie_app/urls.py
from django.urls import path
from . import views

app_name = 'foodie_app'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('recipes/<int:category_id>/', views.ShowView.as_view(), name='show'),
    path('new/', views.NewView.as_view(), name='create'),
]

foodie_app/models.py
from django.db import models

class Category(models.Model):
    # !!! enforces validation at the form and model validation level, but not automatically on .save().
    name = models.CharField(max_length=100, blank=False, null=False, unique=True)
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-name']
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

foodie_app/forms.py
from django import forms
from foodie_app.models import Category

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name']
        labels = {
            'name': 'Category Name',
        }

foodie_app/views.py
from django.shortcuts import get_object_or_404, render
from foodie_app.models import Category
from recipes.models import Recipe
from django.views.generic import ListView, View, CreateView
from foodie_app.forms import CategoryForm

class IndexView(ListView):
    model = Category
    template_name = 'foodie_app/index.html'
    context_object_name = 'categories'

class ShowView(View):
    def get(self, request, *args, **kwargs):
        category_id = kwargs.get('category_id')
        recipes = Recipe.objects.filter(category=category_id)
        category = get_object_or_404(Category, id=category_id)
        context = {
            'recipes': recipes,
            'category': category,
        }
        return render(request, 'recipes/index.html', context)

class NewView(CreateView):
    template_name = 'foodie_app/new.html'
    success_url = '/'
    form_class = CategoryForm

foodie_app/templates/foodie_app/index.html
{% extends "base.html" %}
{% block page_header %}
    <h2>Categories</h2>
{% endblock page_header %}
{% block content %}
    {% if categories %}
        <ul class="list-group list-group-flush">
            {% for category in categories %}
                <li class="list-group-item">
                    <b><a href="{% url 'foodie_app:show' category.id %}" class="link-info link-offset-2 link-underline-opacity-0 link-underline-opacity-25-hover">{{ category }}</a></b>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No categories available.</p>
    {% endif %}
{% endblock content %}

foodie_app/templates/foodie_app/new.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block page_header %}
    <h2>Add new Category</h2>
{% endblock page_header %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form_errors form %}
        {% bootstrap_form form %}
        {% bootstrap_button button_type='submit' content='Save' %}
    </form>
    <div class="mt-5">
        <a href="{% url 'foodie_app:index' %}" class="pt-5 link-primary link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">Back to Categories</a>
    </div>
{% endblock content %}