accounts/urls.py
from django.urls import include, path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('', include('django.contrib.auth.urls')),  # Includes login, logout, password management URLs
]

foodie/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sandbox/', include('sandbox.urls')),
    path('recipes/', include('recipes.urls')),
    path('comments/', include('comments.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('foodie_app.urls')),
]

foodie_app/urls.py
from django.urls import path
from . import views

app_name = 'foodie_app'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('recipes/<int:category_id>/', views.ShowView.as_view(), name='show'),
    path('new/', views.NewView.as_view(), name='create'),
]

recipes/urls.py
from django.urls import path
from . import views

app_name = 'recipes'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>', views.ShowView.as_view(), name='show'),
    path('new/', views.NewView.as_view(), name='new'),
    path('new/category/<int:category_id>/', views.NewView.as_view(), name='new_with_category'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="Foodie - Discover and share amazing recipes.">
        <meta name="keywords" content="food, recipes, cooking, foodie">
        <title>Foddie</title>
        {% load django_bootstrap5 %}
        {% bootstrap_css %}
        {% bootstrap_javascript %}

    </head>
    <body>
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url "foodie_app:index" %}">Foodie App</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        {% if user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% if category %}{% url 'recipes:new_with_category' category.id %}{% else %}{% url 'recipes:new' %}{% endif %}">Add recipe</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'foodie_app:create' %}">Add Category</a>
                            </li>
                        {% endif %}
                    </ul>
                    <div class="d-flex">
                        {% if user.is_authenticated %}
                            <div class="disabled d-inline m-3" aria-disabled="true">Welcome, {{ user }}!</div>
                            <form action="{% url 'accounts:logout' %}" method="post">
                                {% csrf_token %}
                                <button class="btn btn-outline-dark d-inline m-3" type="submit">Logout</button>
                            </form>
                        {% else %}
                            <a class="nav-link active d-inline m-3" aria-current="page" href="{% url 'accounts:login' %}">Login</a>
                            <a class="nav-link active d-inline m-3" aria-current="page" href="{% url 'accounts:register' %}">Register</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </nav>
        <main class="container">
            <div class="p-2 m-2 border-bottom">
                {% block page_header %}
                {% endblock page_header %}
            </div>
            <div class="p-2 m-2">
                {% block content %}
                {% endblock content %}
            </div>
        </main>
    </body>
</html>